/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as ProtectedBookingsRouteImport } from './routes/_protected.bookings'
import { Route as ProtectedCustomersRouteImport } from './routes/_protected.customers'
import { Route as ProtectedDashboardRouteImport } from './routes/_protected.dashboard'
import { Route as ProtectedPaymentsRouteImport } from './routes/_protected.payments'
import { Route as PublicLoginRouteImport } from './routes/_public.login'
import { Route as ProtectedCitiesIndexRouteImport } from './routes/_protected.cities.index'
import { Route as ProtectedCitiesCityIdRouteImport } from './routes/_protected.cities.$cityId'
import { Route as ProtectedCitiesNewRouteImport } from './routes/_protected.cities.new'
import { Route as ProtectedCouponsIndexRouteImport } from './routes/_protected.coupons.index'
import { Route as ProtectedCouponsCouponIdRouteImport } from './routes/_protected.coupons.$couponId'
import { Route as ProtectedCouponsNewRouteImport } from './routes/_protected.coupons.new'
import { Route as ProtectedMoviesIndexRouteImport } from './routes/_protected.movies.index'
import { Route as ProtectedMoviesMovieIdRouteImport } from './routes/_protected.movies.$movieId'
import { Route as ProtectedMoviesNewRouteImport } from './routes/_protected.movies.new'
import { Route as ProtectedShowtimesIndexRouteImport } from './routes/_protected.showtimes.index'
import { Route as ProtectedShowtimesShowIdRouteImport } from './routes/_protected.showtimes.$showId'
import { Route as ProtectedShowtimesNewRouteImport } from './routes/_protected.showtimes.new'
import { Route as ProtectedVenuesIndexRouteImport } from './routes/_protected.venues.index'
import { Route as ProtectedVenuesVenueIdRouteImport } from './routes/_protected.venues.$venueId'
import { Route as ProtectedVenuesNewRouteImport } from './routes/_protected.venues.new'
import { Route as ProtectedCitiesCityIdEditRouteImport } from './routes/_protected.cities.$cityId_.edit'
import { Route as ProtectedCouponsCouponIdEditRouteImport } from './routes/_protected.coupons.$couponId_.edit'
import { Route as ProtectedMoviesMovieIdEditRouteImport } from './routes/_protected.movies.$movieId_.edit'
import { Route as ProtectedVenuesVenueIdEditRouteImport } from './routes/_protected.venues.$venueId_.edit'
import { Route as ProtectedVenuesVenueIdScreensNewRouteImport } from './routes/_protected.venues.$venueId_.screens.new'
import { Route as ProtectedVenuesVenueIdScreensScreenIdEditRouteImport } from './routes/_protected.venues.$venueId_.screens.$screenId_.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedBookingsRoute = ProtectedBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedCustomersRoute = ProtectedCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedDashboardRoute = ProtectedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedPaymentsRoute = ProtectedPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => ProtectedRoute,
} as any)
const PublicLoginRoute = PublicLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => PublicRoute,
} as any)
const ProtectedCitiesIndexRoute = ProtectedCitiesIndexRouteImport.update({
  id: '/cities/',
  path: '/cities/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedCitiesCityIdRoute = ProtectedCitiesCityIdRouteImport.update({
  id: '/cities/$cityId',
  path: '/cities/$cityId',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedCitiesNewRoute = ProtectedCitiesNewRouteImport.update({
  id: '/cities/new',
  path: '/cities/new',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedCouponsIndexRoute = ProtectedCouponsIndexRouteImport.update({
  id: '/coupons/',
  path: '/coupons/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedCouponsCouponIdRoute =
  ProtectedCouponsCouponIdRouteImport.update({
    id: '/coupons/$couponId',
    path: '/coupons/$couponId',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedCouponsNewRoute = ProtectedCouponsNewRouteImport.update({
  id: '/coupons/new',
  path: '/coupons/new',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedMoviesIndexRoute = ProtectedMoviesIndexRouteImport.update({
  id: '/movies/',
  path: '/movies/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedMoviesMovieIdRoute = ProtectedMoviesMovieIdRouteImport.update({
  id: '/movies/$movieId',
  path: '/movies/$movieId',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedMoviesNewRoute = ProtectedMoviesNewRouteImport.update({
  id: '/movies/new',
  path: '/movies/new',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedShowtimesIndexRoute = ProtectedShowtimesIndexRouteImport.update({
  id: '/showtimes/',
  path: '/showtimes/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedShowtimesShowIdRoute =
  ProtectedShowtimesShowIdRouteImport.update({
    id: '/showtimes/$showId',
    path: '/showtimes/$showId',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedShowtimesNewRoute = ProtectedShowtimesNewRouteImport.update({
  id: '/showtimes/new',
  path: '/showtimes/new',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedVenuesIndexRoute = ProtectedVenuesIndexRouteImport.update({
  id: '/venues/',
  path: '/venues/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedVenuesVenueIdRoute = ProtectedVenuesVenueIdRouteImport.update({
  id: '/venues/$venueId',
  path: '/venues/$venueId',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedVenuesNewRoute = ProtectedVenuesNewRouteImport.update({
  id: '/venues/new',
  path: '/venues/new',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedCitiesCityIdEditRoute =
  ProtectedCitiesCityIdEditRouteImport.update({
    id: '/cities/$cityId_/edit',
    path: '/cities/$cityId/edit',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedCouponsCouponIdEditRoute =
  ProtectedCouponsCouponIdEditRouteImport.update({
    id: '/coupons/$couponId_/edit',
    path: '/coupons/$couponId/edit',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedMoviesMovieIdEditRoute =
  ProtectedMoviesMovieIdEditRouteImport.update({
    id: '/movies/$movieId_/edit',
    path: '/movies/$movieId/edit',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedVenuesVenueIdEditRoute =
  ProtectedVenuesVenueIdEditRouteImport.update({
    id: '/venues/$venueId_/edit',
    path: '/venues/$venueId/edit',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedVenuesVenueIdScreensNewRoute =
  ProtectedVenuesVenueIdScreensNewRouteImport.update({
    id: '/venues/$venueId_/screens/new',
    path: '/venues/$venueId/screens/new',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedVenuesVenueIdScreensScreenIdEditRoute =
  ProtectedVenuesVenueIdScreensScreenIdEditRouteImport.update({
    id: '/venues/$venueId_/screens/$screenId_/edit',
    path: '/venues/$venueId/screens/$screenId/edit',
    getParentRoute: () => ProtectedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bookings': typeof ProtectedBookingsRoute
  '/customers': typeof ProtectedCustomersRoute
  '/dashboard': typeof ProtectedDashboardRoute
  '/payments': typeof ProtectedPaymentsRoute
  '/login': typeof PublicLoginRoute
  '/cities/$cityId': typeof ProtectedCitiesCityIdRoute
  '/cities/new': typeof ProtectedCitiesNewRoute
  '/coupons/$couponId': typeof ProtectedCouponsCouponIdRoute
  '/coupons/new': typeof ProtectedCouponsNewRoute
  '/movies/$movieId': typeof ProtectedMoviesMovieIdRoute
  '/movies/new': typeof ProtectedMoviesNewRoute
  '/showtimes/$showId': typeof ProtectedShowtimesShowIdRoute
  '/showtimes/new': typeof ProtectedShowtimesNewRoute
  '/venues/$venueId': typeof ProtectedVenuesVenueIdRoute
  '/venues/new': typeof ProtectedVenuesNewRoute
  '/cities/': typeof ProtectedCitiesIndexRoute
  '/coupons/': typeof ProtectedCouponsIndexRoute
  '/movies/': typeof ProtectedMoviesIndexRoute
  '/showtimes/': typeof ProtectedShowtimesIndexRoute
  '/venues/': typeof ProtectedVenuesIndexRoute
  '/cities/$cityId/edit': typeof ProtectedCitiesCityIdEditRoute
  '/coupons/$couponId/edit': typeof ProtectedCouponsCouponIdEditRoute
  '/movies/$movieId/edit': typeof ProtectedMoviesMovieIdEditRoute
  '/venues/$venueId/edit': typeof ProtectedVenuesVenueIdEditRoute
  '/venues/$venueId/screens/new': typeof ProtectedVenuesVenueIdScreensNewRoute
  '/venues/$venueId/screens/$screenId/edit': typeof ProtectedVenuesVenueIdScreensScreenIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bookings': typeof ProtectedBookingsRoute
  '/customers': typeof ProtectedCustomersRoute
  '/dashboard': typeof ProtectedDashboardRoute
  '/payments': typeof ProtectedPaymentsRoute
  '/login': typeof PublicLoginRoute
  '/cities/$cityId': typeof ProtectedCitiesCityIdRoute
  '/cities/new': typeof ProtectedCitiesNewRoute
  '/coupons/$couponId': typeof ProtectedCouponsCouponIdRoute
  '/coupons/new': typeof ProtectedCouponsNewRoute
  '/movies/$movieId': typeof ProtectedMoviesMovieIdRoute
  '/movies/new': typeof ProtectedMoviesNewRoute
  '/showtimes/$showId': typeof ProtectedShowtimesShowIdRoute
  '/showtimes/new': typeof ProtectedShowtimesNewRoute
  '/venues/$venueId': typeof ProtectedVenuesVenueIdRoute
  '/venues/new': typeof ProtectedVenuesNewRoute
  '/cities': typeof ProtectedCitiesIndexRoute
  '/coupons': typeof ProtectedCouponsIndexRoute
  '/movies': typeof ProtectedMoviesIndexRoute
  '/showtimes': typeof ProtectedShowtimesIndexRoute
  '/venues': typeof ProtectedVenuesIndexRoute
  '/cities/$cityId/edit': typeof ProtectedCitiesCityIdEditRoute
  '/coupons/$couponId/edit': typeof ProtectedCouponsCouponIdEditRoute
  '/movies/$movieId/edit': typeof ProtectedMoviesMovieIdEditRoute
  '/venues/$venueId/edit': typeof ProtectedVenuesVenueIdEditRoute
  '/venues/$venueId/screens/new': typeof ProtectedVenuesVenueIdScreensNewRoute
  '/venues/$venueId/screens/$screenId/edit': typeof ProtectedVenuesVenueIdScreensScreenIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_protected': typeof ProtectedRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/_protected/bookings': typeof ProtectedBookingsRoute
  '/_protected/customers': typeof ProtectedCustomersRoute
  '/_protected/dashboard': typeof ProtectedDashboardRoute
  '/_protected/payments': typeof ProtectedPaymentsRoute
  '/_public/login': typeof PublicLoginRoute
  '/_protected/cities/$cityId': typeof ProtectedCitiesCityIdRoute
  '/_protected/cities/new': typeof ProtectedCitiesNewRoute
  '/_protected/coupons/$couponId': typeof ProtectedCouponsCouponIdRoute
  '/_protected/coupons/new': typeof ProtectedCouponsNewRoute
  '/_protected/movies/$movieId': typeof ProtectedMoviesMovieIdRoute
  '/_protected/movies/new': typeof ProtectedMoviesNewRoute
  '/_protected/showtimes/$showId': typeof ProtectedShowtimesShowIdRoute
  '/_protected/showtimes/new': typeof ProtectedShowtimesNewRoute
  '/_protected/venues/$venueId': typeof ProtectedVenuesVenueIdRoute
  '/_protected/venues/new': typeof ProtectedVenuesNewRoute
  '/_protected/cities/': typeof ProtectedCitiesIndexRoute
  '/_protected/coupons/': typeof ProtectedCouponsIndexRoute
  '/_protected/movies/': typeof ProtectedMoviesIndexRoute
  '/_protected/showtimes/': typeof ProtectedShowtimesIndexRoute
  '/_protected/venues/': typeof ProtectedVenuesIndexRoute
  '/_protected/cities/$cityId_/edit': typeof ProtectedCitiesCityIdEditRoute
  '/_protected/coupons/$couponId_/edit': typeof ProtectedCouponsCouponIdEditRoute
  '/_protected/movies/$movieId_/edit': typeof ProtectedMoviesMovieIdEditRoute
  '/_protected/venues/$venueId_/edit': typeof ProtectedVenuesVenueIdEditRoute
  '/_protected/venues/$venueId_/screens/new': typeof ProtectedVenuesVenueIdScreensNewRoute
  '/_protected/venues/$venueId_/screens/$screenId_/edit': typeof ProtectedVenuesVenueIdScreensScreenIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bookings'
    | '/customers'
    | '/dashboard'
    | '/payments'
    | '/login'
    | '/cities/$cityId'
    | '/cities/new'
    | '/coupons/$couponId'
    | '/coupons/new'
    | '/movies/$movieId'
    | '/movies/new'
    | '/showtimes/$showId'
    | '/showtimes/new'
    | '/venues/$venueId'
    | '/venues/new'
    | '/cities/'
    | '/coupons/'
    | '/movies/'
    | '/showtimes/'
    | '/venues/'
    | '/cities/$cityId/edit'
    | '/coupons/$couponId/edit'
    | '/movies/$movieId/edit'
    | '/venues/$venueId/edit'
    | '/venues/$venueId/screens/new'
    | '/venues/$venueId/screens/$screenId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bookings'
    | '/customers'
    | '/dashboard'
    | '/payments'
    | '/login'
    | '/cities/$cityId'
    | '/cities/new'
    | '/coupons/$couponId'
    | '/coupons/new'
    | '/movies/$movieId'
    | '/movies/new'
    | '/showtimes/$showId'
    | '/showtimes/new'
    | '/venues/$venueId'
    | '/venues/new'
    | '/cities'
    | '/coupons'
    | '/movies'
    | '/showtimes'
    | '/venues'
    | '/cities/$cityId/edit'
    | '/coupons/$couponId/edit'
    | '/movies/$movieId/edit'
    | '/venues/$venueId/edit'
    | '/venues/$venueId/screens/new'
    | '/venues/$venueId/screens/$screenId/edit'
  id:
    | '__root__'
    | '/'
    | '/_protected'
    | '/_public'
    | '/_protected/bookings'
    | '/_protected/customers'
    | '/_protected/dashboard'
    | '/_protected/payments'
    | '/_public/login'
    | '/_protected/cities/$cityId'
    | '/_protected/cities/new'
    | '/_protected/coupons/$couponId'
    | '/_protected/coupons/new'
    | '/_protected/movies/$movieId'
    | '/_protected/movies/new'
    | '/_protected/showtimes/$showId'
    | '/_protected/showtimes/new'
    | '/_protected/venues/$venueId'
    | '/_protected/venues/new'
    | '/_protected/cities/'
    | '/_protected/coupons/'
    | '/_protected/movies/'
    | '/_protected/showtimes/'
    | '/_protected/venues/'
    | '/_protected/cities/$cityId_/edit'
    | '/_protected/coupons/$couponId_/edit'
    | '/_protected/movies/$movieId_/edit'
    | '/_protected/venues/$venueId_/edit'
    | '/_protected/venues/$venueId_/screens/new'
    | '/_protected/venues/$venueId_/screens/$screenId_/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProtectedRoute: typeof ProtectedRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/bookings': {
      id: '/_protected/bookings'
      path: '/bookings'
      fullPath: '/bookings'
      preLoaderRoute: typeof ProtectedBookingsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/customers': {
      id: '/_protected/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof ProtectedCustomersRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/dashboard': {
      id: '/_protected/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof ProtectedDashboardRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/payments': {
      id: '/_protected/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof ProtectedPaymentsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_public/login': {
      id: '/_public/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof PublicLoginRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_protected/cities/': {
      id: '/_protected/cities/'
      path: '/cities'
      fullPath: '/cities/'
      preLoaderRoute: typeof ProtectedCitiesIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/cities/$cityId': {
      id: '/_protected/cities/$cityId'
      path: '/cities/$cityId'
      fullPath: '/cities/$cityId'
      preLoaderRoute: typeof ProtectedCitiesCityIdRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/cities/new': {
      id: '/_protected/cities/new'
      path: '/cities/new'
      fullPath: '/cities/new'
      preLoaderRoute: typeof ProtectedCitiesNewRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/coupons/': {
      id: '/_protected/coupons/'
      path: '/coupons'
      fullPath: '/coupons/'
      preLoaderRoute: typeof ProtectedCouponsIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/coupons/$couponId': {
      id: '/_protected/coupons/$couponId'
      path: '/coupons/$couponId'
      fullPath: '/coupons/$couponId'
      preLoaderRoute: typeof ProtectedCouponsCouponIdRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/coupons/new': {
      id: '/_protected/coupons/new'
      path: '/coupons/new'
      fullPath: '/coupons/new'
      preLoaderRoute: typeof ProtectedCouponsNewRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/movies/': {
      id: '/_protected/movies/'
      path: '/movies'
      fullPath: '/movies/'
      preLoaderRoute: typeof ProtectedMoviesIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/movies/$movieId': {
      id: '/_protected/movies/$movieId'
      path: '/movies/$movieId'
      fullPath: '/movies/$movieId'
      preLoaderRoute: typeof ProtectedMoviesMovieIdRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/movies/new': {
      id: '/_protected/movies/new'
      path: '/movies/new'
      fullPath: '/movies/new'
      preLoaderRoute: typeof ProtectedMoviesNewRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/showtimes/': {
      id: '/_protected/showtimes/'
      path: '/showtimes'
      fullPath: '/showtimes/'
      preLoaderRoute: typeof ProtectedShowtimesIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/showtimes/$showId': {
      id: '/_protected/showtimes/$showId'
      path: '/showtimes/$showId'
      fullPath: '/showtimes/$showId'
      preLoaderRoute: typeof ProtectedShowtimesShowIdRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/showtimes/new': {
      id: '/_protected/showtimes/new'
      path: '/showtimes/new'
      fullPath: '/showtimes/new'
      preLoaderRoute: typeof ProtectedShowtimesNewRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/venues/': {
      id: '/_protected/venues/'
      path: '/venues'
      fullPath: '/venues/'
      preLoaderRoute: typeof ProtectedVenuesIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/venues/$venueId': {
      id: '/_protected/venues/$venueId'
      path: '/venues/$venueId'
      fullPath: '/venues/$venueId'
      preLoaderRoute: typeof ProtectedVenuesVenueIdRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/venues/new': {
      id: '/_protected/venues/new'
      path: '/venues/new'
      fullPath: '/venues/new'
      preLoaderRoute: typeof ProtectedVenuesNewRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/cities/$cityId_/edit': {
      id: '/_protected/cities/$cityId_/edit'
      path: '/cities/$cityId/edit'
      fullPath: '/cities/$cityId/edit'
      preLoaderRoute: typeof ProtectedCitiesCityIdEditRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/coupons/$couponId_/edit': {
      id: '/_protected/coupons/$couponId_/edit'
      path: '/coupons/$couponId/edit'
      fullPath: '/coupons/$couponId/edit'
      preLoaderRoute: typeof ProtectedCouponsCouponIdEditRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/movies/$movieId_/edit': {
      id: '/_protected/movies/$movieId_/edit'
      path: '/movies/$movieId/edit'
      fullPath: '/movies/$movieId/edit'
      preLoaderRoute: typeof ProtectedMoviesMovieIdEditRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/venues/$venueId_/edit': {
      id: '/_protected/venues/$venueId_/edit'
      path: '/venues/$venueId/edit'
      fullPath: '/venues/$venueId/edit'
      preLoaderRoute: typeof ProtectedVenuesVenueIdEditRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/venues/$venueId_/screens/new': {
      id: '/_protected/venues/$venueId_/screens/new'
      path: '/venues/$venueId/screens/new'
      fullPath: '/venues/$venueId/screens/new'
      preLoaderRoute: typeof ProtectedVenuesVenueIdScreensNewRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/venues/$venueId_/screens/$screenId_/edit': {
      id: '/_protected/venues/$venueId_/screens/$screenId_/edit'
      path: '/venues/$venueId/screens/$screenId/edit'
      fullPath: '/venues/$venueId/screens/$screenId/edit'
      preLoaderRoute: typeof ProtectedVenuesVenueIdScreensScreenIdEditRouteImport
      parentRoute: typeof ProtectedRoute
    }
  }
}

interface ProtectedRouteChildren {
  ProtectedBookingsRoute: typeof ProtectedBookingsRoute
  ProtectedCustomersRoute: typeof ProtectedCustomersRoute
  ProtectedDashboardRoute: typeof ProtectedDashboardRoute
  ProtectedPaymentsRoute: typeof ProtectedPaymentsRoute
  ProtectedCitiesCityIdRoute: typeof ProtectedCitiesCityIdRoute
  ProtectedCitiesNewRoute: typeof ProtectedCitiesNewRoute
  ProtectedCouponsCouponIdRoute: typeof ProtectedCouponsCouponIdRoute
  ProtectedCouponsNewRoute: typeof ProtectedCouponsNewRoute
  ProtectedMoviesMovieIdRoute: typeof ProtectedMoviesMovieIdRoute
  ProtectedMoviesNewRoute: typeof ProtectedMoviesNewRoute
  ProtectedShowtimesShowIdRoute: typeof ProtectedShowtimesShowIdRoute
  ProtectedShowtimesNewRoute: typeof ProtectedShowtimesNewRoute
  ProtectedVenuesVenueIdRoute: typeof ProtectedVenuesVenueIdRoute
  ProtectedVenuesNewRoute: typeof ProtectedVenuesNewRoute
  ProtectedCitiesIndexRoute: typeof ProtectedCitiesIndexRoute
  ProtectedCouponsIndexRoute: typeof ProtectedCouponsIndexRoute
  ProtectedMoviesIndexRoute: typeof ProtectedMoviesIndexRoute
  ProtectedShowtimesIndexRoute: typeof ProtectedShowtimesIndexRoute
  ProtectedVenuesIndexRoute: typeof ProtectedVenuesIndexRoute
  ProtectedCitiesCityIdEditRoute: typeof ProtectedCitiesCityIdEditRoute
  ProtectedCouponsCouponIdEditRoute: typeof ProtectedCouponsCouponIdEditRoute
  ProtectedMoviesMovieIdEditRoute: typeof ProtectedMoviesMovieIdEditRoute
  ProtectedVenuesVenueIdEditRoute: typeof ProtectedVenuesVenueIdEditRoute
  ProtectedVenuesVenueIdScreensNewRoute: typeof ProtectedVenuesVenueIdScreensNewRoute
  ProtectedVenuesVenueIdScreensScreenIdEditRoute: typeof ProtectedVenuesVenueIdScreensScreenIdEditRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedBookingsRoute: ProtectedBookingsRoute,
  ProtectedCustomersRoute: ProtectedCustomersRoute,
  ProtectedDashboardRoute: ProtectedDashboardRoute,
  ProtectedPaymentsRoute: ProtectedPaymentsRoute,
  ProtectedCitiesCityIdRoute: ProtectedCitiesCityIdRoute,
  ProtectedCitiesNewRoute: ProtectedCitiesNewRoute,
  ProtectedCouponsCouponIdRoute: ProtectedCouponsCouponIdRoute,
  ProtectedCouponsNewRoute: ProtectedCouponsNewRoute,
  ProtectedMoviesMovieIdRoute: ProtectedMoviesMovieIdRoute,
  ProtectedMoviesNewRoute: ProtectedMoviesNewRoute,
  ProtectedShowtimesShowIdRoute: ProtectedShowtimesShowIdRoute,
  ProtectedShowtimesNewRoute: ProtectedShowtimesNewRoute,
  ProtectedVenuesVenueIdRoute: ProtectedVenuesVenueIdRoute,
  ProtectedVenuesNewRoute: ProtectedVenuesNewRoute,
  ProtectedCitiesIndexRoute: ProtectedCitiesIndexRoute,
  ProtectedCouponsIndexRoute: ProtectedCouponsIndexRoute,
  ProtectedMoviesIndexRoute: ProtectedMoviesIndexRoute,
  ProtectedShowtimesIndexRoute: ProtectedShowtimesIndexRoute,
  ProtectedVenuesIndexRoute: ProtectedVenuesIndexRoute,
  ProtectedCitiesCityIdEditRoute: ProtectedCitiesCityIdEditRoute,
  ProtectedCouponsCouponIdEditRoute: ProtectedCouponsCouponIdEditRoute,
  ProtectedMoviesMovieIdEditRoute: ProtectedMoviesMovieIdEditRoute,
  ProtectedVenuesVenueIdEditRoute: ProtectedVenuesVenueIdEditRoute,
  ProtectedVenuesVenueIdScreensNewRoute: ProtectedVenuesVenueIdScreensNewRoute,
  ProtectedVenuesVenueIdScreensScreenIdEditRoute:
    ProtectedVenuesVenueIdScreensScreenIdEditRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

interface PublicRouteChildren {
  PublicLoginRoute: typeof PublicLoginRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicLoginRoute: PublicLoginRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProtectedRoute: ProtectedRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
